### PR TITLE
Add notify parameter for hipchat notifications to enable notification…

### PR DESCRIPTION
**Pull request by porrl**
… bubble

### CODE REVIEW

**Comment by hjacobs** [comment]
Could you check the Travis CI build (flake8)?

**Comment by porrl** [comment]
I'm not sure what to do with it, as I understand these are some formatting/code convention errors, but it doesn't list the file I've committed, and I have hard time repeating it locally. Can you give me any hints what I should do?

**Comment by hjacobs** [comment]
I'm also wondering why they pop up now, you can do:

```bash
sudo pip3 install --upgrade flake8
python3 setup.py flake8  # in local zmon-worker repository

**Comment by porrl** [comment]
When I run it locally it still prints all this errors, doesn't matter if it's master (without my change) or with my change, and my change is not in the listed files.
Can you merge it anyway? Without the notifications hipchat alerts are not very useful. And I don't think that me fixing all these errors would do any good here.

**Pull request merged**
